export const actionsListBase = {
    SET_THEME: 'SET_THEME',
    SET_THEME_DARK: 'SET_THEME_DARK',
    SET_THEME_LIGHT: 'SET_THEME_LIGHT',
    SET_LANG_EN: 'SET_LANG_EN',
    SET_LANG_RU: 'SET_LANG_RU',
    SET_NAV_MOB_OPEN: 'SET_NAV_MOB_OPEN',
    SET_NAV_MOB_CLOSE: 'SET_NAV_MOB_CLOSE',
    SET_NAV_MOB_TOGGLE: 'SET_NAV_MOB_TOGGLE',
    SET_NAV_DT_OPEN: 'SET_NAV_DT_OPEN',
    SET_NAV_DT_CLOSE: 'SET_NAV_DT_CLOSE',
    SET_NAV_DT_TOGGLE: 'SET_NAV_DT_TOGGLE',
    SET_MODAL: 'SET_MODAL',
}

export const actionsListNews = {
    SET_DATA_NEWS: 'SET_DATA_NEWS',
    SET_DATA_ONE_NEWS: 'SET_DATA_ONE_NEWS',
    SET_TOTAL_NEWS: 'SET_TOTAL_NEWS',
    SET_LOAD_STATUS_NEWS: 'SET_LOAD_STATUS_NEWS',
    SET_LOAD_STATUS_ONE_NEWS: 'SET_LOAD_STATUS_ONE_NEWS',
    SET_SEND_STATUS_NEWS: 'SET_SEND_STATUS_NEWS'
}

export const actionsListFibers = {
    SET_DATA_FIBERS: 'SET_DATA_FIBERS',
    SET_LOAD_STATUS_FIBERS: 'SET_LOAD_STATUS_FIBERS',
    SET_SEND_STATUS_FIBERS: 'SET_SEND_STATUS_FIBERS',
    SET_SELECTED_FIBER: 'SET_SELECTED_FIBER',
}


export const actionsListOrder = {
    SET_ORDER_TEXT: 'SET_ORDER_TEXT',
    SET_ORDER_NAME: 'SET_ORDER_NAME',
    SET_ORDER_PHONE: 'SET_ORDER_PHONE',
    SET_ORDER_EMAIL: 'SET_ORDER_EMAIL',
    CLEAR_ORDER_FORM: 'CLEAR_ORDER_FORM',
    SET_ORDER_FILES: 'SET_ORDER_FILES',
    CLEAR_ORDER_FILES: 'CLEAR_ORDER_FILES',
    SET_SEND_STATUS_ORDER: 'SET_SEND_STATUS_ORDER',
    SET_LOAD_STATUS_ORDER: 'SET_LOAD_STATUS_ORDER',
}


export const actionsListCatalog = {
    SET_LOAD_STATUS_CATEGORIES_LIST: 'SET_LOAD_STATUS_CATEGORIES_LIST',
    SET_SEND_STATUS_CATEGORIES_LIST: 'SET_SEND_STATUS_CATEGORIES_LIST',
    SET_DATA_CATEGORIES_LIST: 'SET_DATA_CATEGORIES_LIST',
    SET_LOAD_STATUS_CATEGORY: 'SET_LOAD_STATUS_CATEGORY',
    SET_DATA_CATEGORY: 'SET_DATA_CATEGORY',
    SET_LOAD_STATUS_PRODUCT: 'SET_LOAD_STATUS_PRODUCT',
    SET_SEND_STATUS_PRODUCT: 'SET_SEND_STATUS_PRODUCT',
    SET_DATA_PRODUCT: 'SET_DATA_PRODUCT',
}


export const actionsListColors = {
    SET_LOAD_STATUS_COLORS: 'SET_LOAD_STATUS_COLORS',
    SET_SEND_STATUS_COLORS: 'SET_SEND_STATUS_COLORS',
    SET_DATA_COLORS: 'SET_DATA_COLORS',
}



export const actionsListUser = {
    SET_USER: 'SET_USER', 
    SET_USER_AUTH: 'SET_USER_AUTH', 
    SET_SEND_STATUS_ORDER: 'SET_SEND_STATUS_ORDER',
    SET_LOAD_STATUS_CART: 'SET_LOAD_STATUS_CART', 
    SET_SEND_STATUS_CART: 'SET_SEND_STATUS_CART', 
    ADD_ITEM_CART: 'ADD_ITEM_CART', 
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    CHANGE_AMOUNT_CART: 'CHANGE_AMOUNT_CART', 
    SET_CART: 'SET_CART'
}


export const actionsListContent = {
    SET_SEND_STATUS_CONTENT: 'SET_SEND_STATUS_CONTENT', 
    SET_LOAD_STATUS_CONTENT: 'SET_LOAD_STATUS_CONTENT', 
    SET_CONTENT: 'SET_CONTENT', 
}


export const actionsListOrders = {
    SET_LOAD_STATUS_ORDERS: 'SET_LOAD_STATUS_ORDERS',
    SET_SEND_STATUS_ORDERS: 'SET_SEND_STATUS_ORDERS',
    SET_ORDERS: 'SET_ORDERS',
    SET_LOAD_USERLIST: 'SET_LOAD_USERLIST',
    SET_USERLIST: 'SET_USERLIST'
}
